services:
  blog-postgres:
    image: postgres:13.3
    container_name: market
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=blog
    ports:
      - '6542:5432'